package com.truedigital.features.truecloudv3.common

object TrueCloudV3SaveStateKey {
    const val KEY_PERMISSION_GRANTED_RESULT = "KEY_PERMISSION_GRANTED_RESULT"
    const val KEY_PERMISSION_GRANTED_RESULT_CATEGORY =
        "KEY_PERMISSION_GRANTED_RESULT_CATEGORY"
    const val KEY_FROM_MIGRATION_PAGE = "KEY_FROM_MIGRATION_PAGE"
    const val KEY_FROM_INIT_MIGRATION_PAGE = "KEY_FROM_INIT_MIGRATION_PAGE"
    const val KEY_TRUE_CLOUD_CONTACT_SYNC_ALL = "KEY_TRUE_CLOUD_CONTACT_SYNC_ALL"
    const val KEY_TRUE_CLOUD_CONTACT_SELECT = "KEY_TRUE_CLOUD_CONTACT_SELECT"
    const val KEY_TRUE_CLOUD_CONTACT_DELETE_ALL = "KEY_TRUE_CLOUD_CONTACT_DELETE_ALL"
    const val KEY_TRUE_CLOUD_CONTACT_EXPORT_TO_DEVICE = "KEY_TRUE_CLOUD_CONTACT_EXPORT_TO_DEVICE"
    const val KEY_TRUE_CLOUD_CONTACT_CAll = "KEY_TRUE_CLOUD_CONTACT_CAll"
    const val KEY_TRUE_CLOUD_CONTACT_DATA = "KEY_TRUE_CLOUD_CONTACT_DATA"
    const val KEY_TRUE_CLOUD_DELETE_CONTACT = "KEY_TRUE_CLOUD_DELETE_CONTACT"
    const val KEY_TRUE_CLOUD_CONTACT_SELECTED_PHONE_LABEL =
        "KEY_TRUE_CLOUD_CONTACT_SELECTED_PHONE_LABEL"
    const val KEY_TRUE_CLOUD_OPTION_MAIN_FILE_SELECT_MODE = "KEY_TRUE_CLOUD_OPTION_MAIN_FILE_SELECT_MODE"
    const val KEY_TRUE_CLOUD_OPTION_MAIN_FILE_SORT_BY = "KEY_TRUE_CLOUD_OPTION_MAIN_FILE_SORT_BY"
    const val KEY_TRUE_CLOUD_OPTION_MAIN_FILE_ADD_NEW_FOLDER = "KEY_TRUE_CLOUD_OPTION_MAIN_FILE_ADD_NEW_FOLDER"
    const val KEY_TRUE_CLOUD_OPTION_FILE_DELETE = "KEY_TRUE_CLOUD_OPTION_FILE_DELETE"
    const val KEY_TRUE_CLOUD_OPTION_FILE_DOWNLOAD = "KEY_TRUE_CLOUD_OPTION_FILE_DOWNLOAD"
    const val KEY_TRUE_CLOUD_OPTION_FILE_RENAME = "KEY_TRUE_CLOUD_OPTION_FILE_RENAME"
    const val KEY_TRUE_CLOUD_OPTION_FILE_INFO = "KEY_TRUE_CLOUD_OPTION_FILE_INFO"
    const val KEY_TRUE_CLOUD_CONTACT_CUSTOM_PHONE_LABEL =
        "KEY_TRUE_CLOUD_CONTACT_CUSTOM_PHONE_LABEL"
    const val KEY_TRUE_CLOUD_CLOSE_SHARE = "KEY_TRUE_CLOUD_CLOSE_SHARE"
    const val KEY_TRUE_CLOUD_SAVE_TO_DEVICE = "KEY_TRUE_CLOUD_SAVE_TO_DEVICE"
    const val KEY_TRUE_CLOUD_SAVE_TO_CLOUD = "KEY_TRUE_CLOUD_SAVE_TO_CLOUD"
    const val KEY_TRUE_CLOUD_FILE_LOCATOR = "KEY_TRUE_CLOUD_FILE_LOCATOR"
    const val KEY_TRUE_CLOUD_OPTION_FILE_GROUP_DELETE = "KEY_TRUE_CLOUD_OPTION_FILE_GROUP_DELETE"
    const val KEY_TRUE_CLOUD_OPTION_MAIN_FILE_EMPTY_TRASH = "KEY_TRUE_CLOUD_OPTION_FILE_EMPTY_TRASH"
    const val KEY_TRUE_CLOUD_OPTION_FILE_PERMANENCE_DELETE = "KEY_TRUE_CLOUD_OPTION_FILE_GROUP_DELETE"
    const val KEY_TRUE_CLOUD_OPTION_FILE_RESTORE = "KEY_TRUE_CLOUD_OPTION_FILE_RESTORE"
    const val KEY_TRUE_CLOUD_PHOTO_EDITOR_IMAGE = "KEY_TRUE_CLOUD_PHOTO_EDITOR_IMAGE"
    const val KEY_TRUE_CLOUD_RELOAD_AFTER_SHARE = "KEY_TRUE_CLOUD_RELOAD_AFTER_SHARE"
    const val KEY_TRUE_CLOUD_PHOTO_EDITOR_TEXT = "KEY_TRUE_CLOUD_PHOTO_EDITOR_TEXT"
}
