package com.truedigital.features.truecloudv3.common

object TrueCloudV3KeyBundle {
    const val KEY_BUNDLE_TRUE_CLOUD_CONTACT_DATA = "KEY_BUNDLE_TRUE_CLOUD_CONTACT_DATA"
    const val KEY_BUNDLE_TRUE_CLOUD_CONTACT_EDIT_PHONE_LABEL_DATA =
        "KEY_BUNDLE_TRUE_CLOUD_CONTACT_EDIT_PHONE_LABEL_DATA"
    const val KEY_BUNDLE_TRUE_CLOUD_OPTION_FILE_MODEL = "KEY_BUNDLE_TRUE_CLOUD_OPTION_FILE_MODEL"
    const val KEY_BUNDLE_TRUE_CLOUD_CONTACT_PHONE_LABEL_DATA =
        "KEY_BUNDLE_TRUE_CLOUD_CONTACT_PHONE_LABEL_DATA"
    const val KEY_BUNDLE_TRUE_CLOUD_FOLDER_ID = "KEY_BUNDLE_TRUE_CLOUD_FOLDER_ID"
    const val KEY_BUNDLE_TRUE_CLOUD_CATEGORY = "KEY_BUNDLE_TRUE_CLOUD_CATEGORY"
    const val KEY_BUNDLE_TRUE_CLOUD_MIGRATE_STATUS = "KEY_BUNDLE_TRUE_CLOUD_MIGRATE_STATUS"
    const val KEY_BUNDLE_TRUE_CLOUD_STORAGE_DETAIL = "KEY_BUNDLE_TRUE_CLOUD_STORAGE_DETAIL"
    const val KEY_BUNDLE_TRUE_CLOUD_SORT_TYPE = "KEY_BUNDLE_TRUE_CLOUD_SORT_TYPE"
    const val KEY_BUNDLE_TRUE_CLOUD_FILE_IMAGE_VIEW = "KEY_BUNDLE_TRUE_CLOUD_FILE_IMAGE_VIEW"
    const val KEY_BUNDLE_TRUE_CLOUD_FILE_VIEW = "KEY_BUNDLE_TRUE_CLOUD_FILE_VIEW"
    const val KEY_BUNDLE_TRUE_CLOUD_FILE_LIST = "KEY_BUNDLE_TRUE_CLOUD_FILE_LIST"
    const val KEY_BUNDLE_TRUE_CLOUD_FILE_PAGE = "KEY_BUNDLE_TRUE_CLOUD_FILE_PAGE"
    const val KEY_BUNDLE_TRUE_CLOUD_FILE_TOTAL_SIZE = "KEY_BUNDLE_TRUE_CLOUD_FILE_TOTAL_SIZE"
    const val KEY_BUNDLE_TRUE_CLOUD_FILE_INFO_MODEL = "KEY_BUNDLE_TRUE_CLOUD_FILE_INFO_MODEL"
    const val KEY_BUNDLE_TRUE_CLOUD_SHARED_FILE = "KEY_BUNDLE_TRUE_CLOUD_SHARED_FILE"
    const val KEY_BUNDLE_TRUE_CLOUD_FILE_ACCESSTOKEN = "KEY_BUNDLE_TRUE_CLOUD_FILE_ACCESSTOKEN"
    const val KEY_BUNDLE_TRUE_CLOUD_SHARED_FILE_ID = "KEY_BUNDLE_TRUE_CLOUD_SHARED_FILE_ID"
    const val KEY_BUNDLE_TRUE_CLOUD_FILE_SELECTED = "KEY_BUNDLE_TURE_CLOUD_FILE_SELECTED"
    const val KEY_BUNDLE_TRUE_CLOUD_FILE_LOCATE_TYPE = "KEY_BUNDLE_TRUE_CLOUD_FILE_LOCATE_TYPE"
    const val KEY_BUNDLE_TRUE_CLOUD_STACK_FOLDER_ID = "KEY_BUNDLE_TRUE_CLOUD_STACK_FOLDER_ID"
    const val KEY_BUNDLE_TRUE_CLOUD_TRASH = "KEY_BUNDLE_TRUE_CLOUD_TRASH"
    const val KEY_BUNDLE_TRUE_CLOUD_OPTION_FOLDER = "KEY_BUNDLE_TRUE_CLOUD_OPTION_FOLDER"
    const val KEY_BUNDLE_TRUE_CLOUD_OPTION_MAIN_TRASH = "KEY_BUNDLE_TRUE_CLOUD_OPTION_MAIN_TRASH"
    const val KEY_BUNDLE_TRUE_CLOUD_DATA_USAGE = "KEY_BUNDLE_TRUE_CLOUD_DATA_UASGE"
    const val KEY_BUNDLE_TRUE_CLOUD_ORIENTATION = "KEY_BUNDLE_TRUE_CLOUD_ORIENTATION"
    const val KEY_BUNDLE_TRUE_CLOUD_PHOTO_EDITOR_IMAGE = "KEY_BUNDLE_TRUE_CLOUD_PHOTO_EDITOR_IMAGE"
}
