
version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          name: Restore Cache Gradle
          keys:
            - jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
            - jars-
      - run:
          name: Install Cloud Google
          command: |
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
      - run:
          name: Install Debian
          command: |
            sudo sed -i s/deb.debian.org/archive.debian.org/g /etc/apt/sources.list
            sudo sed -i 's|security.debian.org|archive.debian.org|g' /etc/apt/sources.list
            sudo sed -i '/stretch-updates/d' /etc/apt/sources.list
      - run:
          name: Install OpenJDK 11
          command: |
            sudo apt update
            sudo add-apt-repository ppa:openjdk-r/ppa
            sudo apt-get update
            sudo apt install openjdk-11-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-11-openjdk-amd64/bin/javac
            java -version
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          name: Save Cache Gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
          paths:
            - ~/.gradle
      - run:
          name: Build Application
          command: ./gradlew clean assembleDebug
      - store_artifacts:
          name: Upload Artifacts Reports
          path: app/build/reports
          destination: reports
      - store_artifacts:
          name: Upload Artifacts Reports
          path: app/build/test-results
      - store_artifacts:
          name: Upload Artifacts File APK
          path: app/build/outputs/apk
          destination: apk